#!/usr/bin/env Rscript
# S42_a2_constants.R - Generate Remark 4 (A2) macros from canonical_facts.md
# Emits: article/a2_constants.tex
# Gates: G1 (all IDs found), G2 (round-trip), G3 (exactly four macros)

# =============================================================================
# Configuration
# =============================================================================
LEDGER_PATH <- "meta/canonical_facts.md"
OUTPUT_PATH <- "article/a2_constants.tex"

# Macro definitions: name -> (ledger_id, precision, is_integer)
# is_integer = TRUE for counts that should render as bare integers
MACROS <- list(
    MomPowMinZ = list(id = "MOMPOW_IDENT_MIN_Z", precision = 2, is_integer = FALSE),
    MomPowMaxZ = list(id = "MOMPOW_IDENT_MAX_Z", precision = 2, is_integer = FALSE),
    AtwoExKurt = list(id = "A2_EXKURT", precision = 3, is_integer = FALSE),
    AtwoExKurtControl = list(id = "A2_EXKURT_CONTROL", precision = 3, is_integer = FALSE),
    HoldoutDThreeMean = list(id = "HOLDOUT_D3_MEAN", precision = 4, is_integer = FALSE),
    HoldoutDThreeN = list(id = "HOLDOUT_D3_N", precision = 0, is_integer = TRUE),
    HoldoutMaxAbsExDThree = list(id = "HOLDOUT_MAX_ABS_EX_D3", precision = 4, is_integer = FALSE)
)

# Expected values for verification
EXPECTED <- list(
    MOMPOW_IDENT_MIN_Z = 2.96,
    MOMPOW_IDENT_MAX_Z = 11.44,
    A2_EXKURT = 0.784,
    A2_EXKURT_CONTROL = -0.269,
    HOLDOUT_D3_MEAN = -0.1013,
    HOLDOUT_D3_N = 314,
    HOLDOUT_MAX_ABS_EX_D3 = 0.0569
)

# =============================================================================
# Parse ledger
# =============================================================================
cat("Reading ledger:", LEDGER_PATH, "\n")
ledger <- readLines(LEDGER_PATH)

parse_ledger_value <- function(ledger_id) {
    # Pattern: | ID | description | value | producer |
    pattern <- sprintf("^\\| %s \\|", ledger_id)
    line <- grep(pattern, ledger, value = TRUE)

    if (length(line) == 0) {
        return(NULL)
    }

    # Split by | and extract value column (third field)
    parts <- strsplit(line, "\\|")[[1]]
    # parts[1] is empty (before first |), parts[2] is ID, parts[3] is desc, parts[4] is value
    value_str <- trimws(parts[4])

    # Handle values with SE: "0.1234 (SE 0.001)" -> extract just the number
    value_str <- sub("\\s*\\(SE.*$", "", value_str)

    as.numeric(value_str)
}

# =============================================================================
# G1: All IDs must be found
# =============================================================================
cat("\n=== G1: Parsing ledger IDs ===\n")
parsed_values <- list()
for (macro_name in names(MACROS)) {
    cfg <- MACROS[[macro_name]]
    val <- parse_ledger_value(cfg$id)

    if (is.null(val) || is.na(val)) {
        stop(sprintf("G1 FAIL: Ledger ID '%s' not found or unparseable", cfg$id))
    }

    parsed_values[[cfg$id]] <- val
    cat(sprintf("  %s = %s (raw: %s)\n", cfg$id, val, val))
}
cat("G1: PASS - all seven IDs found\n")

# =============================================================================
# Verify against expected values
# =============================================================================
cat("\n=== Verification against expected values ===\n")
for (id in names(EXPECTED)) {
    parsed <- parsed_values[[id]]
    expected <- EXPECTED[[id]]

    # Round parsed to expected precision for comparison
    cfg <- MACROS[[names(MACROS)[sapply(MACROS, function(m) m$id == id)]]]
    rounded <- round(parsed, cfg$precision)

    if (abs(rounded - expected) > 1e-9) {
        stop(sprintf(
            "HALT: Parsed value for %s (%.6f -> %.4f) differs from expected (%.4f). Ledger may have moved.",
            id, parsed, rounded, expected
        ))
    }
    cat(sprintf("  %s: %.4f == %.4f OK\n", id, rounded, expected))
}

# =============================================================================
# Generate output file
# =============================================================================
cat("\n=== Generating", OUTPUT_PATH, "===\n")

output_lines <- c(
    "% a2_constants.tex - Auto-generated by S42_a2_constants.R",
    sprintf("%% Generated: %s", format(Sys.time())),
    "%% Appendix A.2: Normality test constants (Remark 4)",
    ""
)

emitted_values <- list()
for (macro_name in names(MACROS)) {
    cfg <- MACROS[[macro_name]]
    raw_val <- parsed_values[[cfg$id]]
    rounded_val <- round(raw_val, cfg$precision)

    # Format the value string
    if (isTRUE(cfg$is_integer)) {
        # Integer: bare number, no decimal point, no thousands separator
        val_str <- as.character(as.integer(rounded_val))
    } else {
        val_str <- format(rounded_val, nsmall = cfg$precision, scientific = FALSE)
    }

    output_lines <- c(output_lines, sprintf("\\newcommand{\\%s}{%s}", macro_name, val_str))
    emitted_values[[macro_name]] <- rounded_val
    cat(sprintf("  \\%s{%s}\n", macro_name, val_str))
}

writeLines(output_lines, OUTPUT_PATH)
cat("Written to", OUTPUT_PATH, "\n")

# =============================================================================
# G2: Round-trip verification
# =============================================================================
cat("\n=== G2: Round-trip verification ===\n")
emitted_content <- readLines(OUTPUT_PATH)
for (macro_name in names(MACROS)) {
    cfg <- MACROS[[macro_name]]
    pattern <- sprintf("\\\\newcommand\\{\\\\%s\\}\\{([^}]+)\\}", macro_name)
    line <- grep(pattern, emitted_content, value = TRUE)

    if (length(line) == 0) {
        stop(sprintf("G2 FAIL: Macro \\%s not found in emitted file", macro_name))
    }

    match <- regmatches(line, regexec(pattern, line))[[1]]
    reparsed <- as.numeric(match[2])
    original <- emitted_values[[macro_name]]

    if (abs(reparsed - original) > 1e-9) {
        stop(sprintf("G2 FAIL: \\%s round-trip failed: %.6f != %.6f",
                     macro_name, reparsed, original))
    }
    cat(sprintf("  \\%s: %.4f == %.4f OK\n", macro_name, reparsed, original))
}
cat("G2: PASS - all values round-trip correctly\n")

# =============================================================================
# G3: Exactly four macros
# =============================================================================
cat("\n=== G3: Macro count verification ===\n")
newcommand_lines <- grep("^\\\\newcommand", emitted_content, value = TRUE)
n_macros <- length(newcommand_lines)
cat(sprintf("  Macros defined: %d\n", n_macros))

stopifnot("G3 FAIL: Expected exactly 7 macros" = n_macros == 7)
cat("G3: PASS - exactly seven macros defined\n")

cat("\n=== All gates passed ===\n")
